### ISSUE TITLE
Could you update this?

### ISSUE THREAD

**Issue by nanoqsh** [digama0/dae-parser#2]
`cargo build` of this crate warns:
```
warning: the following packages contain code that will be rejected by a future version of Rust: quick-xml v0.22.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`
```

Could you please update dependencies, in particular the warning comes from [minidom](https://docs.rs/minidom/0.15.1/minidom/) crate.

**Comment by digama0** [comment]
I investigated this some time ago, and it appears that minidom 0.15 is a massively breaking change, changing many of the intermediate types and switching out the `quick_xml` backend (which was pub re-exported in the old version and used extensively in this crate) for `rxml`. I would rather just fork the old version. (But also, not really, I don't want to be responsible for maintaining a DOM crate. I'll be happy to depend on someone else who wants to do that instead.)

**Comment by digama0** [comment]
I looked into minidom and rxml again, and now I can say with more confidence that this crate is not implementable on the new version - key data structures are private, which makes it impossible to simultaneously do SAX-based event parsing and DOM element creation. So the options are either to ditch minidom and use rxml with a custom `Element` type, or stick with 0.14 and quick-xml. At least with a fork of 0.14 we could update the transitive dependency on quick-xml that is causing the problem...
