### ISSUE TITLE
Primitives enum element has diferent types

### ISSUE THREAD

**Issue by EtaLoop** [digama0/dae-parser#6]
Some element of `Primitives` enum have their field `data.prim` wrapped in `Option<T>` (`Lines`, `Triangles`), some don't (`LineStrips`, `PolyList`, `TriFans`, `TriStrips`).

**Comment by digama0** [comment]
I'm afraid this is out of cache for me, but I'm certain that this was not an accident (or at least, adding/removing optionality is something I do consciously). Looking at the code, I see that the `validate` function for `Lines` and `Triangles` treats the `None` and `Some([])` cases differently: a `None` is ignored, while a `Some([])` is only valid if the `count` is actually zero. So I guess there is somewhere else where data-less `LineGeom`s are being used for something?

For the others, there is some clue here (6ea2a4b), which removed optionality from `PolyListGeom`, probably after seeing how it was used in the wild. (The spec says that the element is optional and is somewhat vague about what that means.)

**Comment by EtaLoop** [comment]
Okay, was just to make sure it was on purpose :wink:
